### PR TITLE
i LOVE purely untested code!

### PR DESCRIPTION
**Pull request by vivianexists**
PLEASEEEE END MY SUFFERING

### CODE REVIEW

**Comment by Glitchtest51** [comment]
aint no way you caztually did it im sorry what 😭

**Comment by vivianexists** [comment]
i expect this to NOT work at all

**Comment by vivianexists** [comment]
if it actually does work i would be shocked

**Comment by vivianexists** [comment]
AND IT DOESN'T WORK I WAS RIGHT!!

**Pull request closed without merging**
